name: flutter_wisy_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  camerawesome: ^1.4.0
  go_router: ^6.0.4
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.1
  freezed: ^2.3.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true