// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrpdUtmwe415AaFYjU2bAP4JYbRMeVJM',
    appId: '1:770976105802:web:5fdd7e10c2de8910de6db3',
    messagingSenderId: '770976105802',
    projectId: 'flutter-wisy-app',
    authDomain: 'flutter-wisy-app.firebaseapp.com',
    storageBucket: 'flutter-wisy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1alJPnd1aTbFXXzKc9580_dTiYrToAM',
    appId: '1:770976105802:android:c46d014e05f7b40bde6db3',
    messagingSenderId: '770976105802',
    projectId: 'flutter-wisy-app',
    storageBucket: 'flutter-wisy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqG9XBOs5z8LfUt4AtzW13ULVELon1VQ',
    appId: '1:770976105802:ios:1553760a7db164fede6db3',
    messagingSenderId: '770976105802',
    projectId: 'flutter-wisy-app',
    storageBucket: 'flutter-wisy-app.appspot.com',
    iosClientId: '770976105802-34aivhm4ehj5bg7kj6ar0m0g2ktr11os.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWisyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqG9XBOs5z8LfUt4AtzW13ULVELon1VQ',
    appId: '1:770976105802:ios:4d5be8a53e5305d9de6db3',
    messagingSenderId: '770976105802',
    projectId: 'flutter-wisy-app',
    storageBucket: 'flutter-wisy-app.appspot.com',
    iosClientId: '770976105802-867kdnqmsm01nerik69d7181obi0t8i0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWisyApp.RunnerTests',
  );
}
